import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import HeroBanner from '@/components/Hero-Banner'
import Products from '@/components/Products'
import 'react-whatsapp-widget/dist/index.css'
import {getFeaturedProduct, urlFor} from '@/utils/sanity'

const inter = Inter({subsets: ['latin']})

type Product = {
  _id: string
  name: string
  description: string
  price: number
  category: {
    _id: string
    title: string
  }
  image: any
  rating: number
}
interface Props {
  product: Product
}

export default function Home({product}: Props) {

  const heroProps = {
    imageSrc: urlFor(product.image[0].asset._ref).url(),
    title: product?.name,
    subtitle: product?.description || 'Adorn Yourself with Exquisite Jewelry Creations',
    id: product?.category?._id || '',
  }

  return (
    <>
      <Head>
        <title>Teetoobeez | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div className="flex flex-col">
            {product ? <HeroBanner {...heroProps} /> : <p className="text-4xl text-center font-bold my-4">No featured product available.</p>}
            <Products />
          </div>
        </Layout>
      </main>
    </>
    /* IUC 7038708688(0) */
  )
}

export const getStaticProps = async () => {
  const product = await getFeaturedProduct()

  return {
    props: {product},
    revalidate: 1, // Set this to a higher value if you don't need to update the data frequently
  }
}
