import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import HeroBanner from '@/components/Hero-Banner'
import Products from '@/components/Products'
import "react-whatsapp-widget/dist/index.css";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Teetoobeez</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div className="flex flex-col">
            <HeroBanner />
            <Products />
          </div>
        </Layout>
      </main>
    </>
  )
}
